### ISSUE TITLE
Could you explain why you used abi.encodePacked?

### ISSUE THREAD

**Issue by shafiquejamal** [owanhunte/ethereum-solidity-course-updated-code#1]
Hello, many thanks for providing this repo! Would you be able to explain why you used [abi.encodePacked](https://solidity.readthedocs.io/en/v0.6.0/abi-spec.html) ?
```
        return int256(keccak256(abi.encodePacked(block.difficulty, block.number, players)));
```

Thanks,

**Comment by owanhunte** [comment]
Hi @shafiquejamal, one of the main breaking changes introduced from Solidity version 0.5.0 was a change in arguments accepted by the keccak256() and sha256() functions, among others. These 2 functions no longer accept multiple arguments as shown in the course code Lottery smart contract example. Instead they now accept a single `bytes` argument, a change that [according to the Solidity docs](https://solidity.readthedocs.io/en/v0.6.0/050-breaking-changes.html#semantic-and-syntactic-changes), was made to **make more explicit and clear how the arguments are concatenated**.

The abi.encodePacked() function performs [packed encoding](https://solidity.readthedocs.io/en/v0.6.0/abi-spec.html#abi-packed-mode) of the given arguments and returns (`bytes memory`).

The consequence of this breaking change was that every call to `keccak256(a, b, c)` now required a change to `keccak256(abi.encodePacked(a, b, c))`.

**Comment by owanhunte** [comment]
Hi @shafiquejamal I hope I was able to adequately answer your question (I'm going to assume I did based on your thumbs-up :)). I'm going to leave this issue open for now for the benefit of others.

Happy new year and all the best in your endeavours!

**Comment by shafiquejamal** [comment]
Hello @owanhunte, yes you answered my question very well, thanks! Happy new year and all the best to you too!
