### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by olenderhub** [owanhunte/ethereum-solidity-course-updated-code#38]
https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/9f9fc1048526699252222ceca9d1bb32c8c6e31d/kickstart/ethereum/compile.js#L49-L50

I think you can use 

```
    const element = contracts[contract];
    fs.outputJsonSync(path.resolve(buildPath, `${contract}.json`), element);
```

**Comment by owanhunte** [comment]
@olenderhub Thanks for pointing that out. I thought I had actually made such a change to that file when I started the refactoring of this repo for Solidity 0.8. I'll make the change now.
